// This file is generated by rust-protobuf 3.2.0. Do not edit
// .proto file is parsed by protoc 3.19.4
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `xresloader.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_2_0;

/// Extension fields
pub mod exts {

    pub const file_description: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::std::string::String> = ::protobuf::ext::ExtFieldOptional::new(1001, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_STRING);

    pub const msg_description: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, ::std::string::String> = ::protobuf::ext::ExtFieldOptional::new(1001, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_STRING);

    pub const msg_require_mapping_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(1011, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const msg_separator: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, ::std::string::String> = ::protobuf::ext::ExtFieldOptional::new(1012, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_STRING);

    pub const validator: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FieldOptions, ::std::string::String> = ::protobuf::ext::ExtFieldOptional::new(1001, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_STRING);

    pub const field_unique_tag: ::protobuf::ext::ExtFieldRepeated<::protobuf::descriptor::FieldOptions, ::std::string::String> = ::protobuf::ext::ExtFieldRepeated::new(1002, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_STRING);

    pub const field_not_null: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FieldOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(1003, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const map_key_validator: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FieldOptions, ::std::string::String> = ::protobuf::ext::ExtFieldOptional::new(1004, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_STRING);

    pub const map_value_validator: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FieldOptions, ::std::string::String> = ::protobuf::ext::ExtFieldOptional::new(1005, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_STRING);

    pub const verifier: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FieldOptions, ::std::string::String> = ::protobuf::ext::ExtFieldOptional::new(1009, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_STRING);

    pub const field_description: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FieldOptions, ::std::string::String> = ::protobuf::ext::ExtFieldOptional::new(1011, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_STRING);

    pub const field_alias: ::protobuf::ext::ExtFieldRepeated<::protobuf::descriptor::FieldOptions, ::std::string::String> = ::protobuf::ext::ExtFieldRepeated::new(1012, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_STRING);

    pub const field_ratio: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FieldOptions, i32> = ::protobuf::ext::ExtFieldOptional::new(1013, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_INT32);

    pub const field_separator: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FieldOptions, ::std::string::String> = ::protobuf::ext::ExtFieldOptional::new(1014, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_STRING);

    pub const field_required: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FieldOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(1015, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const field_origin_value: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FieldOptions, ::std::string::String> = ::protobuf::ext::ExtFieldOptional::new(1016, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_STRING);

    pub const oneof_description: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::OneofOptions, ::std::string::String> = ::protobuf::ext::ExtFieldOptional::new(1001, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_STRING);

    pub const oneof_separator: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::OneofOptions, ::std::string::String> = ::protobuf::ext::ExtFieldOptional::new(1002, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_STRING);

    pub const oneof_not_null: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::OneofOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(1003, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const enum_description: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::EnumOptions, ::std::string::String> = ::protobuf::ext::ExtFieldOptional::new(1001, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_STRING);

    pub const enumv_description: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::EnumValueOptions, ::std::string::String> = ::protobuf::ext::ExtFieldOptional::new(1001, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_STRING);

    pub const enum_alias: ::protobuf::ext::ExtFieldRepeated<::protobuf::descriptor::EnumValueOptions, ::std::string::String> = ::protobuf::ext::ExtFieldRepeated::new(1002, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_STRING);
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x10xresloader.proto\x12\x0eorg.xresloader\x1a\x20google/protobuf/desc\
    riptor.proto:H\n\x10file_description\x18\xe9\x07\x20\x01(\t\x12\x1c.goog\
    le.protobuf.FileOptionsR\x0ffileDescription:I\n\x0fmsg_description\x18\
    \xe9\x07\x20\x01(\t\x12\x1f.google.protobuf.MessageOptionsR\x0emsgDescri\
    ption:W\n\x17msg_require_mapping_all\x18\xf3\x07\x20\x01(\x08\x12\x1f.go\
    ogle.protobuf.MessageOptionsR\x14msgRequireMappingAll:E\n\rmsg_separator\
    \x18\xf4\x07\x20\x01(\t\x12\x1f.google.protobuf.MessageOptionsR\x0cmsgSe\
    parator:<\n\tvalidator\x18\xe9\x07\x20\x01(\t\x12\x1d.google.protobuf.Fi\
    eldOptionsR\tvalidator:H\n\x10field_unique_tag\x18\xea\x07\x20\x03(\t\
    \x12\x1d.google.protobuf.FieldOptionsR\x0efieldUniqueTag:D\n\x0efield_no\
    t_null\x18\xeb\x07\x20\x01(\x08\x12\x1d.google.protobuf.FieldOptionsR\
    \x0cfieldNotNull:J\n\x11map_key_validator\x18\xec\x07\x20\x01(\t\x12\x1d\
    .google.protobuf.FieldOptionsR\x0fmapKeyValidator:N\n\x13map_value_valid\
    ator\x18\xed\x07\x20\x01(\t\x12\x1d.google.protobuf.FieldOptionsR\x11map\
    ValueValidator::\n\x08verifier\x18\xf1\x07\x20\x01(\t\x12\x1d.google.pro\
    tobuf.FieldOptionsR\x08verifier:K\n\x11field_description\x18\xf3\x07\x20\
    \x01(\t\x12\x1d.google.protobuf.FieldOptionsR\x10fieldDescription:?\n\
    \x0bfield_alias\x18\xf4\x07\x20\x03(\t\x12\x1d.google.protobuf.FieldOpti\
    onsR\nfieldAlias:?\n\x0bfield_ratio\x18\xf5\x07\x20\x01(\x05\x12\x1d.goo\
    gle.protobuf.FieldOptionsR\nfieldRatio:G\n\x0ffield_separator\x18\xf6\
    \x07\x20\x01(\t\x12\x1d.google.protobuf.FieldOptionsR\x0efieldSeparator:\
    E\n\x0efield_required\x18\xf7\x07\x20\x01(\x08\x12\x1d.google.protobuf.F\
    ieldOptionsR\rfieldRequired:L\n\x12field_origin_value\x18\xf8\x07\x20\
    \x01(\t\x12\x1d.google.protobuf.FieldOptionsR\x10fieldOriginValue:K\n\
    \x11oneof_description\x18\xe9\x07\x20\x01(\t\x12\x1d.google.protobuf.One\
    ofOptionsR\x10oneofDescription:G\n\x0foneof_separator\x18\xea\x07\x20\
    \x01(\t\x12\x1d.google.protobuf.OneofOptionsR\x0eoneofSeparator:D\n\x0eo\
    neof_not_null\x18\xeb\x07\x20\x01(\x08\x12\x1d.google.protobuf.OneofOpti\
    onsR\x0coneofNotNull:H\n\x10enum_description\x18\xe9\x07\x20\x01(\t\x12\
    \x1c.google.protobuf.EnumOptionsR\x0fenumDescription:O\n\x11enumv_descri\
    ption\x18\xe9\x07\x20\x01(\t\x12!.google.protobuf.EnumValueOptionsR\x10e\
    numvDescription:A\n\nenum_alias\x18\xea\x07\x20\x03(\t\x12!.google.proto\
    buf.EnumValueOptionsR\tenumAliasb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(1);
            deps.push(::protobuf::descriptor::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(0);
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
